test 1

diff --git a/.github/workflows/c-cpp.yml b/.github/workflows/c-cpp.yml
--- a/.github/workflows/c-cpp.yml
+++ b/.github/workflows/c-cpp.yml
@@ -20,11 +20,31 @@ jobs:
     
     steps:
     - uses: actions/checkout@v4
+      # Runs the configure script, to configure the build environment
     - name: configure
       run: ./configure
-    - name: make
-      run: make
+      # Runs cmake using the makefile
+    - name: find makefile and make
+      run: |
+        export MAKEFILE=Source/makefile
+        make -f $MAKEFILE
+      # Runs any tests defined in the MAKEFILE to verify that the build is working correctly
     - name: make check
       run: make check
+      # Runs a distribution check, which is used to create a distribution of the package,
+      # then perform tests to ensure that it can be built and installed properly from the distribution
     - name: make distcheck
-      run: make distcheck
+      run: |
+        echo "Running distribution check..."
+        make distcheck
+      # tee output.log logs the output of the program
+      # check if output contains <text> using grep -q <text>
+    - name: run the program and check whether the output is correct
+      run: |
+        ./Source/main | tee output.log | grep -q "Hello, World!"
+        if [ $? -ne 0 ]; then
+          echo "Test failed. Closing..."
+          exit 1
+        fi
+        echo "Test Passed..."
+
